### PR TITLE
Share to Viber/Whatsapp not working inside iframe on iOS Safari

### LINKED ISSUE #11: Share to Viber/Whatsapp not working inside iframe on iOS Safari

### PR DESCRIPTION
**Pull request by mkhazov**
closes #11

### CODE REVIEW

File: src/sharers/viber.js [hunk 1]
```diff
@@ -10,5 +11,5 @@ export default function viber(options = {}) {
     text: [title, url].filter(item => item).join(' '),
   });
 
-  return window.location.assign(`viber://forward?${params}`);
+  return mobileShare(`viber://forward?${params}`);
```
Comment (avdeev) [inline src/sharers/viber.js]: You need to check mobileShare call instead of location.assign in the sharers/viber test

File: src/sharers/whatsapp.js [hunk 2]
```diff
@@ -7,5 +8,5 @@ export default function whatsapp(options = {}) {
     text: [title, url].filter(item => item).join(' '),
   });
 
-  return window.location.assign(`whatsapp://send?${params}`);
+  return mobileShare(`whatsapp://send?${params}`);
```
Comment (avdeev) [inline src/sharers/whatsapp.js]: You need to check mobileShare call instead of location.assign in the sharers/whatsapp test

**Comment by mkhazov** [comment]
yeah, forgot to update sharers tests
